base:
  param:
    homePage: "redirect:http://www.bilibili.com"
    loginPage: "redirect:http://auth.bilibili.com/login.html"
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bilibili?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: 123456
mybatis:
  type-aliases-package: com.bilibili.entity
  mapper-locations: classpath:/mapper/*.xml
server:
  servlet:
    context-path: /api
