logging:
  config: classpath:logback.xml
base:
  param:
    homePage: "redirect:http://www.bilibili.com"
    loginPage: "redirect:http://auth.bilibili.com/login.html"
    tempLocation: "C:/Users/79301/Desktop/file/"
    fileLocation: "C:/Users/79301/Desktop/file/"
#    tempLocation: "/root/bili/src/video/"
#    fileLocation: "/root/bili/src/video/"
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 793012545@qq.com #发送邮件的邮箱地址
    nickname: 模仿Bilibli的视频弹幕网站
    password: wovdlxsmjagabbjd #客户端授权码
    from: 793012545@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/bilibili?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 1.116.112.80
    port: 16379
    timeout: 20000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: vming793012545
mybatis:
  type-aliases-package: com.bilibili.entity
  mapper-locations: classpath:/mapper/*.xml
server:
  servlet:
    context-path: /api

#rocketmq配置信息
rocketmq:
  #nameservice服务器地址（多个以英文逗号隔开）
  name-server: 1.116.112.80:9876
  #生产者配置
  producer:
    #组名
    group: anran-producer-group
    #目的地（topic:tag）
    #topic
    topic: anran-topic
    #sync tag(同步消息tag)
    sync-tag: anran-sync-tags
    #async tag(异步消息tag)
    async-tag: anran-async-tags
    #oneway tag(单向消息tag)
    oneway-tag: anran-oneway-tags

  #消费者配置
  consumer:
    #组名
    group: anran-consumer-group
    #监听主题
    topic: anran-topic
    #tags（监听多个tag时使用 || 进行分割，如果监听所有使用*或者不填）
    tags: anran-sync-tags||anran-async-tags||anran-oneway-tags

